export const ACTION_CONSTANTS = {
  GET_APP_VIEW: {
    SUCCESS: 'GET_APP_VIEW/SUCCESS',
    FAILURE: 'GET_APP_VIEW/FAILURE'
  },
  UPDATE_APP_VIEW: {
    SUCCESS: 'UPDATE_APP_STATE/SUCCESS',
    FAILURE: 'UPDATE_APP_STATE/FAILURE'
  }
};
